### ISSUE TITLE
Pinview doesnt show

### ISSUE THREAD

**Issue by saravanan72** [pankajbhandari08/customPin#2]
Hi, I try this example to do with pinview. when i click enter pin, it doesnt show the view.

**Comment by fujahgabriel** [comment]
This is how i got it to work.
in my page.module.ts
i added the following below;

`import { NgModule,CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { ComponentsModule } from '../../components/components.module';
import { YourPage } from './page';

@NgModule({
  declarations: [
    YourPage,
  ],
  imports: [
    ComponentsModule,
    IonicPageModule.forChild(YourPage),
  ],
  exports: [
    YourPage,
  ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class YourPageModule { }`


then in pin.html under component/pin/

i removed the `<ion-content>` 

and make sure you change the selector from custom-pin to pin 

from
` <custom-pin *ngIf="ShowPin" pagetitle="Enter The Pin" (change)="eventCapture($event)"></custom-pin>`

to
` <pin *ngIf="ShowPin" pagetitle="Enter The Pin" (change)="eventCapture($event)"></pin>`
